version: '3.8'

services:
    selenium:
        container_name: selenium-chrome
        shm_size: 2g
        image: selenium/standalone-chrome
        ports:
            - "4444:4444"

    app:
        container_name: bot
        image: visasolution-bot-app:latest
        build: .
        command: ["/app/main", "-email", "${EMAIL}", "-interval", "${INTERVAL}"]
        restart: always
        ports:
            - "2525:2525"
        environment:
            - SELENIUM_URL=http://selenium:4444/wd/hub
        volumes:
            - visasolution-logs:/app/logs
        depends_on:
            - selenium

volumes:
    visasolution-logs:
        driver: local